version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
        - echo "installing..."

  pre_build:
    commands:
      - echo "pre build phase"

  build:
    commands:
      - echo "we are in the build block"
      - echo "we will run some tests"
      - grep -Fq "Congratulations" index.html

  post_build:
    commands:
      - echo "post build phase"
    
